"""The head part: skull and face skin with eye and mouth openings, eyeballs, lashes, brows, mouth interior, ears, blush,
and the face morphs, all generated from the spec ([head] table + [proportions] + [colors]).

Overview (see the head_* modules):
  head_shape  implicit head (visual hull of a front and a side outline + blobs + neck), head-local coordinates
  head_skin   (theta, phi) grid of that shape with holes, ring zones, neck ring
  head_eye    eye opening, eyeball placement, lid rings, eyeball layers (sclera, iris, pupil, highlights)
  ...
The head is built in HEAD-LOCAL metres (origin at the head bone, Reisen-sized) and placed in model space with
`Frame(pivot, scale)`.

`[head]` keys (all optional): source ("param" (default): the face is generated by this module; "body": the face comes from
the imported base the body part publishes, see head_body), scale (default [proportions] s_head, else 1), skin / eyes
colours override [colors.*]. The generated face below is the "param" mode; `published` (the info the hair and the outfit fit
to) is shared by both modes."""
from types import SimpleNamespace

import numpy as np

from ..build import builder
from ..part import Material, Mesh, Morph, Part
from . import head_brow as HB
from . import head_decal as DC
from . import head_ear as HR
from . import head_eye as EY
from . import head_info as HI
from . import head_lid as HL
from . import head_morph as HM
from . import head_mouth as MO
from . import head_shape as HS
from . import head_skin as SK
from . import head_tex as TX

NECK, HEAD, EYE_L, EYE_R = "首", "頭", "左目", "右目"

M_SKIN, M_SCLERA, M_IRIS, M_PUPIL, M_HIGHLIGHT = "顔", "白目", "瞳", "瞳孔", "ハイライト"
M_LASH, M_LASH_LOW, M_CREASE, M_BROW = "睫毛", "下睫毛", "二重", "眉毛"
M_LIP, M_MOUTH, M_TONGUE, M_TEETH, M_BLUSH = "口線", "口内", "舌", "歯", "チーク"
M_LIPC = "口角"


class Frame:
    """Head-local <-> model space: model = pivot + scale * local."""

    def __init__(self, pivot, scale):
        self.pivot = np.asarray(pivot, float)
        self.s = float(scale)

    def to_model(self, P):
        return self.pivot + self.s * np.asarray(P, float)

    def to_local(self, P):
        return (np.asarray(P, float) - self.pivot) / self.s


class MeshAcc:
    """Accumulates mesh pieces (vertices, faces, per-corner uv, material, bone weights) into one Mesh."""

    def __init__(self, name):
        self.name = name
        self.V, self.F, self.UV, self.FM, self.N = [], [], [], [], []
        self.W = []                       # per vertex {bone: weight}
        self.mats = []
        self.pieces = {}                  # piece name -> (vertex range)

    def mat(self, name):
        if name not in self.mats:
            self.mats.append(name)
        return self.mats.index(name)

    def add(self, piece, verts, faces, mat, weights, uv=None, normals=None, corner_uv=None):
        """weights: {bone: float | (n,) array}. uv: (n, 2) per vertex (expanded to face corners); corner_uv: one list of
        (u, v) per face (face corner order) when a vertex needs different uv in different faces (a map seam)."""
        base = len(self.V)
        verts = np.asarray(verts, float)
        n = len(verts)
        self.V.extend(verts)
        mi = self.mat(mat)
        for k, f in enumerate(faces):
            self.F.append(tuple(int(i) + base for i in f))
            self.FM.append(mi)
            if corner_uv is not None:
                self.UV.extend(tuple(c) for c in corner_uv[k])
            elif uv is not None:
                self.UV.extend(tuple(uv[i]) for i in f)
            else:
                self.UV.extend((0.0, 0.0) for _ in f)
        w = {k: (np.full(n, float(v)) if np.isscalar(v) else np.asarray(v, float)) for k, v in weights.items()}
        for i in range(n):
            self.W.append({k: float(a[i]) for k, a in w.items() if a[i] > 0})
        if normals is None:
            self.N.extend([None] * n)
        else:
            self.N.extend(list(np.asarray(normals, float)))
        self.pieces[piece] = (base, base + n)
        return np.arange(base, base + n)

    def vertex_normals(self):
        V = np.asarray(self.V)
        N = np.zeros_like(V)
        for f in self.F:
            for k in range(1, len(f) - 1):
                a, b, c = V[f[0]], V[f[k]], V[f[k + 1]]
                n = np.cross(b - a, c - a)
                for i in (f[0], f[k], f[k + 1]):
                    N[i] += n
        N /= np.maximum(np.linalg.norm(N, axis=1, keepdims=True), 1e-12)
        return N

    def mesh(self, frame, morphs=None, smooth=True):
        V = frame.to_model(np.asarray(self.V))
        N = np.asarray([n if n is not None else (0.0, 0.0, 0.0) for n in self.N], float)
        calc = self.vertex_normals()
        none = np.array([n is None for n in self.N])
        N[none] = calc[none]
        bones = sorted({k for w in self.W for k in w})
        weights = {b: np.array([w.get(b, 0.0) for w in self.W]) for b in bones}
        m = Mesh(self.name, verts=V, faces=self.F, uv=np.asarray(self.UV, float), face_mat=np.asarray(self.FM, int),
                 mats=list(self.mats), weights=weights, normals=N, smooth=smooth)
        if morphs:
            m.morphs = {k: frame.s * np.asarray(v, float) for k, v in morphs.items()}
        return m


def vertex_normals(V, F):
    """Area-weighted vertex normals of a polygon list."""
    V = np.asarray(V, float)
    N = np.zeros_like(V)
    for f in F:
        for k in range(1, len(f) - 1):
            n = np.cross(V[f[k]] - V[f[0]], V[f[k + 1]] - V[f[0]])
            for i in (f[0], f[k], f[k + 1]):
                N[i] += n
    return N / np.maximum(np.linalg.norm(N, axis=1, keepdims=True), 1e-12)


def _proxy_phi(P):
    """The smooth chubby proxy of the face: an ellipsoid plus the cheek apples and a soft jaw volume (pseudo-distance)."""
    d = HS.ellipsoid(P, (0.0, -0.012, 0.085), (0.095, 0.102, 0.118))
    for sx in (1.0, -1.0):
        d = HS.smin(d, HS.ellipsoid(P, (sx * 0.050, -0.072, 0.016), (0.034, 0.030, 0.026)), 0.022)
    return HS.smin(d, HS.ellipsoid(P, (0.0, -0.076, -0.010), (0.036, 0.030, 0.022)), 0.022)


def skin_normals(shape, V, blend=0.65):
    """Smooth anime-face normals: the gradient of the implicit head mixed with the gradient of the chubby proxy, so the toon
    terminator is a big soft curve that follows the cheek and the jaw and nose, lids and mouth add no shading noise. At the
    seam ring the normals are horizontal radial like the body's top rings."""
    g = shape.normal(V)
    h = 2e-3
    e = np.zeros_like(V)
    for k in range(3):
        d = np.zeros(3)
        d[k] = h
        e[:, k] = _proxy_phi(V + d) - _proxy_phi(V - d)
    e /= np.maximum(np.linalg.norm(e, axis=1, keepdims=True), 1e-12)
    b = (blend * SK.smooth((V[:, 2] + 0.022) / 0.016))[:, None]
    out = (1 - b) * g + b * e
    out /= np.maximum(np.linalg.norm(out, axis=1, keepdims=True), 1e-12)
    ring_z = getattr(shape, "ring_z", None)
    if ring_z is not None:
        nk = shape.p["neck"]
        rad = np.stack([V[:, 0] - nk["c"][0], V[:, 1] - nk["c"][1], np.zeros(len(V))], -1)
        rad /= np.maximum(np.linalg.norm(rad, axis=1, keepdims=True), 1e-12)
        w = (1.0 - SK.smooth((V[:, 2] - ring_z) / 0.012))[:, None]
        out = (1 - w) * out + w * rad
        out /= np.maximum(np.linalg.norm(out, axis=1, keepdims=True), 1e-12)
    return out


def orient(P, faces):
    """Flip faces that run clockwise seen from the front (x right, z up)."""
    out = []
    for f in faces:
        a = 0.0
        for i in range(len(f)):
            p, q = P[f[i]], P[f[(i + 1) % len(f)]]
            a += p[0] * q[2] - q[0] * p[2]
        out.append(tuple(f) if a >= 0 else tuple(reversed(f)))
    return out


def bind_strip(surf, lo_xz, hi_xz, height, tip=False, ends_pointed=False, nudge=0.0, normal_xz=None):
    """Bind a strip given by its two edges (k, 2) in the front plane. Returns (Decal, faces) with vertex 2k = lo[k],
    2k+1 = hi[k]; with `tip` the last cross-section is the single vertex hi[-1]; with `ends_pointed` the first and last
    cross-sections collapse to one vertex each. `nudge` moves the lo edge that far along `normal_xz` (into the skin,
    away from a hole's margin) so it binds to a triangle."""
    lo = np.asarray(lo_xz, float).copy()
    hi = np.asarray(hi_xz, float)
    k = len(lo)
    if nudge and normal_xz is not None:
        lo = lo + nudge * normal_xz
    pts = np.empty((2 * k, 2))
    pts[0::2], pts[1::2] = lo, hi
    keep = np.ones(2 * k, bool)
    remap = np.arange(2 * k)
    if tip:
        keep[2 * k - 2] = False
        remap[2 * k - 2] = 2 * k - 1
    if ends_pointed:
        keep[0] = False
        remap[0] = 1
        keep[2 * k - 2] = False
        remap[2 * k - 2] = 2 * k - 1
    idx = np.cumsum(keep) - 1
    tri, bary = surf.bind(pts[keep][:, 0], pts[keep][:, 1])
    dec = DC.Decal(surf, tri, bary, height)
    faces = []
    for q in range(k - 1):
        a0, a1, b0, b1 = (idx[remap[2 * q]], idx[remap[2 * q + 1]], idx[remap[2 * q + 2]], idx[remap[2 * q + 3]])
        uniq = []
        for v in (a0, b0, b1, a1):
            if not uniq or uniq[-1] != v:
                uniq.append(int(v))
        if len(uniq) > 1 and uniq[0] == uniq[-1]:
            uniq.pop()
        if len(uniq) >= 3:
            faces.append(tuple(uniq))
    DC.clear_skin(dec, faces)
    return dec, faces


def skin_uv(V, F, yc):
    """Per-corner uv of the face skin on the cylindrical map (head_tex.face_skin): u from the azimuth about the head axis
    (unwrapped per face so a face across the back seam stays contiguous), v from the height."""
    th = np.arctan2(V[:, 0], -(V[:, 1] - yc))
    v = np.clip((V[:, 2] - TX.UV_Z0) / (TX.UV_Z1 - TX.UV_Z0), 0.0, 1.0)
    out = []
    for f in F:
        t = th[list(f)]
        t = t + 2 * np.pi * np.round((t[0] - t) / (2 * np.pi))
        out.append([(0.5 + float(a) / (2 * np.pi), float(v[i])) for a, i in zip(t, f)])
    return out


def mix_hex(a, b, t):
    c = TX.hex_rgb(a) * (1 - t) + TX.hex_rgb(b) * t
    return "#%02x%02x%02x" % tuple(int(round(float(x) * 255)) for x in c)


def anchors_from(prop, frame, own=None):
    """Head-shape anchors (head_shape.ANCHORS, head-local metres) from the spec's [proportions.head] and
    [proportions.face] named numbers; anything missing keeps the default."""
    h = (prop or {}).get("head") or {}
    f = (prop or {}).get("face") or {}
    s = frame.s
    pv = frame.pivot
    A = {}

    def yz(y, z):
        return ((float(y) - pv[1]) / s, (float(z) - pv[2]) / s)
    if "crown_skull" in h:
        A["crown"] = ((float(h.get("crown_y", pv[1] - 0.0088 * s)) - pv[1]) / s, (float(h["crown_skull"]) - pv[2]) / s)
    for key, wkey, zkey in (("temple", "width_max", 1.325), ("eye", "width_eye_level", None), ("cheek", "width_cheek", 1.226),
                            ("mouth", "width_mouth", 1.207), ("chin", "width_chin", 1.187)):
        if wkey in h:
            z = zkey if zkey is not None else float(f.get("eye_z", pv[2] + 0.0563 * s))
            A[key] = ((z - pv[2]) / s, float(h[wkey]) / 2.0 / s)
    if "chin_point" in h:
        A["chin_point"] = yz(*h["chin_point"])
    if "forehead_front" in h:
        A["forehead"] = yz(*h["forehead_front"])
    for k, v in (own or {}).items():                  # [head.shape] overrides (head.toml)
        A[k] = v
    return A


def colors_of(ctx):
    c = ctx.get("colors", {}) or {}
    cfg = ctx.cfg or {}
    out = {}
    for k in ("skin", "eyes", "mouth"):
        d = dict(c.get(k, {}))
        d.update(cfg.get(k, {}) or {})
        out[k] = d
    return out


@builder("head", needs=("body",))
def build(ctx):
    cfg = ctx.cfg or {}
    if cfg.get("source", "param") == "body":                    # the face imported with the body (head_body)
        from . import head_body
        return head_body.build(ctx)
    prop = ctx.spec.get("proportions") or {}
    body = ctx.need("body")
    land = ctx.land
    pivot = np.asarray(land["head"], float)
    scale = float(cfg.get("scale", 1.0))
    frame = Frame(pivot, scale)
    col = colors_of(ctx)
    face_p = prop.get("face") or {}
    guides = prop.get("hair_guides") or {}

    # ---- the shape, with the neck of the body
    nt = body.info["neck_top"]
    nc = frame.to_local(np.array([nt["center"][0], nt["center"][1], nt["z"]]))
    shape = HS.HeadShape(anchors_from(prop, frame, cfg.get("shape")),
                         neck=dict(c=(0.0, float(nc[1]), 0.0), rx=nt["rx"] / scale, ry=nt["ry"] / scale, k=0.014, top=0.02))
    grid_cfg = dict(n_cols=80, face_deg=2.1, spacing_face=0.0042, spacing_neck=0.0048, spacing_top=0.0070,
                    ring_z=float(nc[2]))
    grid_cfg.update(cfg.get("grid", {}))
    shape.ring_z = grid_cfg["ring_z"]
    grid = SK.Grid(shape, grid_cfg)
    sb = SK.SkinBuilder(shape, grid)
    eye_cfg = dict(cfg.get("eye") or {})
    if "eye_x" in face_p and "iris" not in eye_cfg:
        eye_cfg["iris"] = (float(face_p.get("iris_x", 0.0422)) / scale, (float(face_p["eye_z"]) - pivot[2]) / scale)
    if "eye.L" in land and "centre_y" not in eye_cfg:             # the eye bone (made by the body part) is the pivot
        eye_cfg["centre_y"] = float(frame.to_local(land["eye.L"])[1])
    eyes = {side: EY.add_eye(sb, side, eye_cfg) for side in ("L", "R")}
    for side, e in eyes.items():
        want = land.get(f"eye.{side}")
        if want is not None and np.abs(frame.to_model(e["E"]) - want).max() > 5e-4:
            ctx.log(f"WARNING eye.{side} landmark {np.round(want, 4).tolist()} differs from the eyeball centre "
                    f"{np.round(frame.to_model(e['E']), 4).tolist()}: the eye bone would pivot off the eyeball")
    mouth_cfg = dict(cfg.get("mouth") or {})
    if "mouth_z" in face_p and "z" not in mouth_cfg:
        mouth_cfg["z"] = (float(face_p["mouth_z"]) - pivot[2]) / scale
    if "mouth_width" in face_p and "half_width" not in mouth_cfg:
        mouth_cfg["half_width"] = 0.5 * float(face_p.get("mouth_width_rest", 0.036)) / scale
    mouth = MO.add_mouth(sb, mouth_cfg)
    EY.apply_dips(sb, list(eyes.values()))
    sb.build_grid_faces()
    V, F, group, remap = sb.finish()
    mouth["ids"] = [remap[r] for r in mouth["rings"]]
    mouth["ids3"] = mouth["ids"][3]

    # ---- the skin mesh
    face = MeshAcc("face")
    nrm = skin_normals(shape, V)
    t = SK.smooth((V[:, 2] - grid_cfg["ring_z"]) / 0.020)
    face.add("skin", V, F, M_SKIN, {HEAD: t, NECK: 1.0 - t}, normals=nrm, corner_uv=skin_uv(V, F, float(shape.centre[1])))
    mi_lash = face.mat(M_LASH)
    col3 = {}
    for e in eyes.values():                                   # ring-3 vertex -> (is an upper-lid column)
        for c_i, vid in enumerate(remap[e["rings"][3]]):
            col3[int(vid)] = bool(e["upper"][c_i])
    for fi, f in enumerate(F):
        if group[fi] == SK.SkinBuilder.RIM and any(col3.get(int(v), False) for v in f[:2]):
            face.FM[fi] = mi_lash                              # the inner lid rim under the upper lash is lash-coloured


    # ---- the eyes
    eye_mesh = MeshAcc("eyes")
    for side, e in eyes.items():
        parts = EY.eyeball_parts(e)
        bone = EYE_L if side == "L" else EYE_R
        for pname, (pv, pf, puv) in parts.items():
            mat = {"sclera": M_SCLERA, "iris": M_IRIS, "pupil": M_PUPIL}.get(pname, M_HIGHLIGHT)
            w = {HEAD: 1.0} if pname == "sclera" else {bone: 1.0}
            rad = np.stack([np.zeros(len(pv)), -np.ones(len(pv)), np.zeros(len(pv))], -1)       # the eyes face forward
            eye_mesh.add(f"{pname}.{side}", pv, pf, mat, w, uv=puv, normals=rad)

    # ---- lines on the skin: lashes, creases, brows (bound to the skin)
    surf = DC.SkinSurface(V, F, group)
    lines = MeshAcc("lines")
    decals, strips = {}, {}
    for side, e in eyes.items():
        sg, (cx, cz) = e["sign"], e["centre"]
        for name, shape_fn, mat, h in (("lash", EY.upper_lash, M_LASH, EY.LASH_HEIGHT),
                                       ("lashlow", EY.lower_lash, M_LASH_LOW, EY.LASH_HEIGHT * 0.9),
                                       ("crease", EY.crease, M_CREASE, EY.LASH_HEIGHT * 0.8)):
            sh = shape_fn(e, cfg.get(name))
            lo = np.stack([cx + sg * sh["lo"][:, 0], cz + sh["lo"][:, 1]], -1)
            hi = np.stack([cx + sg * sh["hi"][:, 0], cz + sh["hi"][:, 1]], -1)
            nrm_xz = None
            if "normal" in sh:
                nrm_xz = np.stack([sg * sh["normal"][:, 0], sh["normal"][:, 1]], -1)
            dec, faces = bind_strip(surf, lo, hi, h, tip=sh.get("tip", False), ends_pointed=sh.get("ends_pointed", False),
                                    nudge=6e-5, normal_xz=nrm_xz)
            P = dec.positions()
            lines.add(f"{name}.{side}", P, orient(P, faces), mat, {HEAD: 1.0})
            decals[f"{name}.{side}"] = dec
            if name == "lash":                                  # lid parameter of every cross-section
                m = len(sh["margin"])
                d = np.concatenate([[0.0], np.cumsum(np.linalg.norm(np.diff(sh["lo"][:m], axis=0), axis=1))])
                wn = int(EY.UPPER_LASH["wing_n"])
                sp = np.concatenate([d / d[-1], 1.0 + np.arange(1, wn) / (wn - 1) * 0.30])
            else:
                c = dict(EY.LOWER_LASH if name == "lashlow" else EY.CREASE)
                c.update(cfg.get(name) or {})
                sp = np.linspace(c["s0"], c["s1"], c["n"])
            strips[f"{name}.{side}"] = dict(lo=sh["lo"], hi=sh["hi"], tip=sh.get("tip", False),
                                            ends_pointed=sh.get("ends_pointed", False), h=h, s=sp)
    brow_cfg = dict(cfg.get("brow") or {})
    if "brow_z" in face_p and "z" not in brow_cfg:
        brow_cfg["z"] = (float(face_p["brow_z"]) - pivot[2]) / scale
    if "brow_x" in face_p and "x" not in brow_cfg:
        brow_cfg["x"] = tuple(float(v) / scale for v in face_p["brow_x"])
    brows = {}
    for side, sg in (("L", 1.0), ("R", -1.0)):
        cl, w = HB.centreline(brow_cfg)
        lo, hi = HB.edges(cl, w)
        lo, hi = lo * [sg, 1.0], hi * [sg, 1.0]
        dec, faces = bind_strip(surf, lo, hi, HB.BROW["height"], tip=True)
        P = dec.positions()
        lines.add(f"brow.{side}", P, orient(P, faces), M_BROW, {HEAD: 1.0})
        decals[f"brow.{side}"] = dec
        brows[side] = cl * [sg, 1.0]

    # ---- a hint of nose: one tiny stroke under the tip
    xs = np.linspace(-0.0034, 0.0034, 11)
    zs = 0.0258 + 0.0012 * (xs / 0.0034) ** 2
    taper = np.sin(np.pi * np.linspace(0, 1, 11)) ** 0.7 * 0.0007
    dec, faces = bind_strip(surf, np.stack([xs, zs], -1), np.stack([xs, zs + taper], -1), 0.0003, ends_pointed=True)
    P = dec.positions()
    lines.add("nose", P, orient(P, faces), M_CREASE, {HEAD: 1.0})

    # ---- anime lids: skin-coloured sheets tucked behind the lid margins (the skin itself never moves for a blink)
    lids_mesh = MeshAcc("lids")
    lids = {sd: HL.Lids(shape, e) for sd, e in eyes.items()}
    sheets = {}
    for sd, L in lids.items():
        sheets[sd] = {}
        for which in ("upper", "lower"):
            Pr, Fq, v_top = L.sheet_rest_and_faces(which)
            Pt = L.sheet_target(which, v_top, L.arc(0.0062))
            Fo = orient(Pt, Fq)
            rows = lids_mesh.add(f"{which}lid.{sd}", Pr, Fo, M_SKIN, {HEAD: 1.0}, normals=skin_normals(shape, Pt),
                                 corner_uv=skin_uv(Pr, Fo, float(shape.centre[1])))
            sheets[sd][which] = (rows, v_top)

    # ---- the mouth: lip lines (on the skin) and the interior behind the slit
    for key, (lo, hi) in MO.lip_line_edges(mouth["cfg"]).items():
        dec, faces = bind_strip(surf, lo, hi, MO.DEFAULTS["line_width"] * 0 + 0.00035, ends_pointed=True)
        P = dec.positions()
        lines.add(f"lip{key}", P, orient(P, faces), M_LIP, {HEAD: 1.0})
        decals[f"lip{key}"] = dec
    hwm = mouth["cfg"]["half_width"]                                  # a tiny darker accent that turns up at each corner
    zc = float(MO.slit_z(mouth["cfg"], np.array([hwm]))[0])
    tt = np.linspace(0.0, 1.0, 5)
    for sgx, nm in ((1.0, "L"), (-1.0, "R")):
        x = sgx * (hwm - 0.0006 + 0.0018 * tt)
        z = zc + 0.0012 * tt
        dec, faces = bind_strip(surf, np.stack([x, z], -1), np.stack([x, z + np.sin(np.pi * tt) ** 0.7 * 0.00075], -1), 0.0004,
                                ends_pointed=True)
        P = dec.positions()
        lines.add(f"lipcorner.{nm}", P, orient(P, faces), M_LIPC, {HEAD: 1.0})
        decals[f"lipcorner.{nm}"] = dec
    mouth_mesh = MeshAcc("mouth")
    cv, cf, cuv, cfollow, ccols = MO.cavity(mouth, V)
    mouth["cav_follow"], mouth["cav_cols"] = cfollow, ccols
    n_ring = mouth["n"]
    mouth_mesh.add("cavity", cv, cf, M_MOUTH, {HEAD: 1.0}, uv=cuv)
    A_front = cv[:n_ring]
    tv, tf, txs = MO.teeth_geometry(A_front, mouth)
    mouth_mesh.add("teeth", tv, orient(tv, tf), M_TEETH, {HEAD: 1.0})
    tgv, tgf = MO.tongue_geometry(A_front, mouth)
    mouth_mesh.add("tongue", tgv, tgf, M_TONGUE, {HEAD: 1.0})

    # ---- blush overlay for 照れ: a big soft patch on each cheek, hidden 1.2 mm under the skin until the morph raises it
    blush = MeshAcc("blush")
    blush_up = {}
    bc = dict(centre=(0.050, 0.012), semi=(0.031, 0.0115), hide=-0.0012, show=0.0005, nx=13, nz=7)
    bc.update(cfg.get("blush") or {})
    for side, sg in (("L", 1.0), ("R", -1.0)):
        gx, gz = np.meshgrid(np.linspace(-1, 1, bc["nx"]), np.linspace(-1, 1, bc["nz"]))
        x = sg * bc["centre"][0] + sg * gx.ravel() * bc["semi"][0] * np.sqrt(np.clip(1 - 0.5 * gz.ravel() ** 2, 0.3, 1))
        z = bc["centre"][1] + gz.ravel() * bc["semi"][1]
        d = np.stack([x, np.full_like(x, -0.085) - shape.centre[1], z - shape.centre[2]], -1)
        d /= np.linalg.norm(d, axis=1, keepdims=True)
        P0 = shape.surface(d)
        N0 = shape.normal(P0)
        Ph = P0 + bc["hide"] * N0
        nx = bc["nx"]
        quads = [(j * nx + i, j * nx + i + 1, (j + 1) * nx + i + 1, (j + 1) * nx + i) for j in range(bc["nz"] - 1)
                 for i in range(nx - 1)]
        uv = np.stack([0.5 + 0.5 * gx.ravel(), 0.5 + 0.5 * gz.ravel()], -1)
        blush.add(f"blush.{side}", Ph, orient(Ph, quads), M_BLUSH, {HEAD: 1.0}, uv=uv, normals=N0)
        blush_up[side] = (P0 + bc["show"] * N0) - Ph

    # ---- ears
    ears = MeshAcc("ears")
    ear_info = {}
    P, Fe, einfo = HR.ear(shape, cfg.get("ear"))
    for side, sg in (("L", 1.0), ("R", -1.0)):
        Pm = P * [sg, 1.0, 1.0]
        Fm = Fe if sg > 0 else [tuple(reversed(f)) for f in Fe]
        ears.add(f"ear.{side}", Pm, Fm, M_SKIN, {HEAD: 1.0})
        ear_info[side] = {k: (np.asarray(v) * [sg, 1.0, 1.0]) for k, v in einfo.items()}

    # ---- morphs
    H = SimpleNamespace(V=V, surf=surf, decals=decals, lines=lines, eyes=eye_mesh, lids=lids, sheets=sheets,
                        lids_mesh=lids_mesh, strips=strips, eyes_info=eyes, brows=brows, bind_strip=bind_strip, brow_cfg=brow_cfg, mouth=mouth,
                        mouth_mesh=mouth_mesh, teeth_x=txs)
    M = HM.Morpher(H)
    HM.build_eye_and_brow_morphs(M)
    HM.build_mouth_morphs(M)
    book = M.book
    book.sizes["blush"] = len(blush.V)
    for side in ("L", "R"):
        book.add(HM.NAMES["blush"][0], "blush", blush_up[side], np.arange(*blush.pieces[f"blush.{side}"]))

    # ---- materials and textures
    skin_col = TX.hex_rgb(col["skin"].get("base", "#f1e7d6"))
    # the face and neck share the body's skin look: [head.skin] overrides, else what the body published, else [colors.skin]
    own = (ctx.cfg or {}).get("skin") or {}
    bskin = body.info.get("skin") or {}
    # the face looks straight into the key light, so its lit base is a touch warmer than the body's near-white (it clips to a
    # white mask otherwise); [head.skin] base overrides
    skin_base = own.get("base") or "#fcf6ea"
    toon_mult = own.get("face_toon_multiplier") or bskin.get("toon_mult") or (0.957, 0.827, 0.843)
    bmat = next((m for m in body.materials if m.name == bskin.get("material", "skin")), None)
    shared = dict(diffuse=(1.0, 1.0, 1.0, 1.0), specular=(0.0, 0.0, 0.0), shininess=0.0, ambient=(0.5, 0.5, 0.5))
    if bmat is not None:
        shared = dict(diffuse=bmat.diffuse, specular=bmat.specular, shininess=bmat.shininess, ambient=bmat.ambient)
    if own.get("ambient"):
        shared["ambient"] = tuple(float(v) for v in own["ambient"])
    skin_ambient = shared["ambient"]
    cheek_col = own.get("cheek") or col["skin"].get("cheek") or bskin.get("blush") or "#f09a96"
    nsh = body.info.get("neck_shadow") or {}                       # the body's baked neck shadow: continue it up to the jaw
    # the face keeps its own ramp: white wherever the studio light is above a low threshold, the light rosy shadow colour only
    # in real shadow. A body-style ramp (edge 0.42) puts a studio-lit face on the transition and turns it pink-grey.
    toon = bskin["toon"] if own.get("use_body_toon") and bskin.get("toon") else ctx.save_png(
        "toon", TX.toon(toon_mult, height=32, edge=float(own.get("toon_edge", 0.30)), soft=float(own.get("toon_soft", 0.14))))
    skin_tex = ctx.save_png("skin", TX.face_skin(
        skin_base, cheek_col, cheek_k=0.40, jaw=HI.jaw_line(shape, 512), band=nsh.get("color", "#e3aa95"),
        band_w=(float(nsh.get("strength", 0.9)), float(nsh.get("front", 1.0)), float(nsh.get("back", 0.35)))))
    iris_tex = ctx.save_png("iris", TX.iris(col["eyes"]))
    sclera_cols = dict(col["eyes"])
    sclera_cols["sclera"] = mix_hex(sclera_cols.get("sclera", "#f6f1f2"), "#ffffff", 0.45)
    sclera_cols["sclera_shadow"] = mix_hex(sclera_cols.get("sclera_shadow", "#cfc8d6"), "#ffffff", 0.25)
    sclera_tex = ctx.save_png("sclera", TX.sclera(sclera_cols, EY.sclera_frame(), skin=skin_base, shade=float(cfg.get("lash_shadow", 0.22))))
    white = ctx.save_png("white_sphere", TX.white_sphere())
    edge = TX.hex_rgb(col["skin"].get("outline", "#8a6a62"))

    def flat_mat(name, name_en, hexcol, k=0.9, **kw):
        """A flat colour: mmd_tools shades (ambient + diffuse) x light, so the two share `k` of the colour."""
        c = TX.hex_rgb(hexcol)
        d, a = 0.62 * k * c, 0.38 * k * c
        return Material(name, name_en=name_en, diffuse=(float(d[0]), float(d[1]), float(d[2]), 1.0),
                        ambient=(float(a[0]), float(a[1]), float(a[2])), toon="", edge=False,
                        drop_shadow=False, self_shadow=False, self_shadow_map=False, **kw)
    ec = col["eyes"]
    blush_tex = ctx.save_png("blush", TX.blush(col["skin"].get("blush_morph", "#ee7a86")))
    mats = [
        Material(M_SKIN, name_en="face", diffuse=shared["diffuse"], specular=shared["specular"],
                 shininess=shared["shininess"], ambient=skin_ambient, texture=skin_tex, toon=toon, edge=True,
                 edge_color=(float(edge[0]), float(edge[1]), float(edge[2]), 1.0), edge_size=0.5,
                 self_shadow=False, self_shadow_map=False),
        Material(M_SCLERA, name_en="sclera", diffuse=(1, 1, 1, 1), ambient=(0.5, 0.5, 0.5), texture=sclera_tex,
                 toon="", edge=False, drop_shadow=False, self_shadow=False, self_shadow_map=False),
        Material(M_IRIS, name_en="iris", diffuse=(0.62, 0.62, 0.62, 1), ambient=(0.38, 0.38, 0.38), texture=iris_tex,
                 toon="", edge=False, drop_shadow=False, self_shadow=False, self_shadow_map=False),
        flat_mat(M_PUPIL, "pupil", ec.get("pupil", "#1f0307"), k=0.8),
        Material(M_HIGHLIGHT, name_en="highlight", diffuse=(0, 0, 0, 1), ambient=(1, 1, 1), sphere=white,
                 sphere_mode="add", toon="", edge=False, drop_shadow=False, self_shadow=False, self_shadow_map=False),
        flat_mat(M_LASH, "upper lash", ec.get("lash", "#2a0a10"), k=0.75),
        flat_mat(M_LASH_LOW, "lower lash", mix_hex(ec.get("lash_lower", "#6b1d2a"), "#d0606a", 0.45), k=0.85),
        flat_mat(M_CREASE, "eyelid crease", mix_hex(ec.get("lid_crease", "#c97b6c"), "#7a3a30", 0.35), k=0.9),
        flat_mat(M_BROW, "eyebrow", ec.get("brow", "#7a1218"), k=0.8),
        flat_mat(M_LIP, "lip line", mix_hex(col["mouth"].get("lip_line", "#c7a19a"), "#a24f5a", 0.65), k=0.9),
        flat_mat(M_LIPC, "mouth corners", mix_hex(col["mouth"].get("lip_line", "#c7a19a"), "#7a2c38", 0.7), k=0.85),
        flat_mat(M_MOUTH, "mouth interior", col["mouth"].get("interior", "#7a1824"), k=0.85),
        flat_mat(M_TONGUE, "tongue", col["mouth"].get("tongue", "#e8727f"), k=0.9),
        flat_mat(M_TEETH, "teeth", col["mouth"].get("teeth", "#fffaf2"), k=0.95),
        Material(M_BLUSH, name_en="blush", diffuse=(0.62, 0.62, 0.62, 0.62), ambient=(0.38, 0.38, 0.38), texture=blush_tex,
                 toon="", edge=False, alpha_blend=True, drop_shadow=False, self_shadow=False, self_shadow_map=False),
    ]

    def morphs_of(mesh_name):
        return {k: v[mesh_name] for k, v in book.data.items() if mesh_name in v}
    meshes = [face.mesh(frame, morphs_of("face")), eye_mesh.mesh(frame, morphs_of("eyes")),
              lines.mesh(frame, morphs_of("lines")), lids_mesh.mesh(frame, morphs_of("lids")),
              mouth_mesh.mesh(frame, morphs_of("mouth")), ears.mesh(frame), blush.mesh(frame, morphs_of("blush"))]
    declared = {v[0]: Morph(v[0], v[1], v[2]) for v in HM.NAMES.values()}
    morph_list = [declared[k] for k in book.names() if k in declared]

    # ---- published information (model space)
    info = published(shape, frame, eyes, brows, ear_info, nc, guides, nt, grid_cfg)
    info["lid_margin"] = {}
    for sd, e in eyes.items():
        ids3 = remap[e["rings"][3]]
        up = e["upper"].copy()
        up[[e["inner"], e["outer"]]] = True
        lo = ~e["upper"]
        lo[[e["inner"], e["outer"]]] = True
        info["lid_margin"][sd] = dict(upper=ids3[up], lower=ids3[lo], inner=int(ids3[e["inner"]]), outer=int(ids3[e["outer"]]),
                                      mesh="face")
    info["mouth"] = dict(slit_upper=mouth["ids3"][mouth["upper"]], slit_lower=mouth["ids3"][mouth["lower"]],
                         centre=frame.to_model(np.array([0.0, float(np.mean(V[mouth["ids3"]][:, 1])), mouth["cfg"]["z"]])),
                         half_width=mouth["cfg"]["half_width"], mesh="face")
    return Part("head", meshes=meshes, materials=mats, bones=[], morphs=morph_list, info=info)


def neck_ring(nt, n=32):
    """The neck seam ring (n, 3) in model space: the body's ring when it published one, else its ellipse."""
    if nt.get("ring") is not None:
        return np.asarray(nt["ring"], float)
    a = 2 * np.pi * np.arange(n) / n
    return np.stack([nt["center"][0] + nt["rx"] * np.sin(a), nt["center"][1] - nt["ry"] * np.cos(a),
                     np.full(n, float(nt["z"]))], -1)


def published(shape, frame, eyes, brows, ear_info, nc, guides, nt, grid_cfg, ring_ids=None, custom=None):
    """The info dict: see the notes sent to the hair part (keys documented in docs/design.md: Characters).
    `custom` (the PMX mode, head_pmxbuild): {"eye_info": {side: {...}}, "landmarks": {...}, "skin": (verts, triangles)} in
    model space replace what is otherwise computed from the parametric `eyes` and the implicit shape's own shell."""
    custom = custom or {}
    M = frame.to_model
    prof = shape.prof
    zc = float(shape.centre[2])
    if "skin" in custom:
        Vs_m, Ts = custom["skin"]
    else:
        Vs, Ts = HI.skin_shell(shape, grid_cfg["ring_z"])
        Vs_m = M(Vs)
    tz = float(guides.get("hairline_centre_z", frame.pivot[2] + 0.1828 * frame.s))
    temple = guides.get("hairline_temple", [0.0936, frame.pivot[2] + 0.1256 * frame.s])
    front, side, nape = HI.hairline(shape, (tz - frame.pivot[2]) / frame.s,
                                    (temple[0] / frame.s, (temple[1] - frame.pivot[2]) / frame.s))
    hw_c, yf_c, yb_c = (float(a) for a in prof.at(zc))
    A = prof.a
    # the face outline: left temple -> hairline -> right temple -> down the right sideburn -> jaw -> chin -> left jaw ->
    # up the left sideburn (closed loop on the skin)
    zj = float(side["L"][-1][2])
    zz = np.linspace(zj, A["chin_point"][1] + 0.0015, 9)
    hw = prof.at(zz)[0] * 0.90
    jaw_r = SK.lift(shape, -hw, zz)
    jaw_l = SK.lift(shape, hw[::-1], zz[::-1])
    chin = SK.lift(shape, np.zeros(1), np.array([A["chin_point"][1] + 0.0015]))
    outline = np.vstack([front, side["R"][1:], jaw_r, chin, jaw_l, side["L"][::-1][:-1]])
    eye_info = dict(custom.get("eye_info") or {})
    for sd, e in ({} if eye_info else eyes).items():
        sg = e["sign"]
        up = np.nonzero(e["upper"])[0]
        lo = np.nonzero(~e["upper"])[0]
        P3 = None
        poly = e["alm"].poly
        xz = np.stack([e["centre"][0] + sg * poly[:, 0], np.zeros(len(poly)), e["centre"][1] + poly[:, 1]], -1)
        eye_info[sd] = dict(center=M(e["E"]), radius=e["radius"] * frame.s, pupil=M(e["E"] + np.array([0.0, -e["radius"], 0.0])),
                            opening=M(xz)[:, [0, 2]])
    info = dict(
        frame=dict(pivot=frame.pivot, scale=frame.s),
        landmarks=custom.get("landmarks") or {f"eye.{s}": M(e["E"]) for s, e in eyes.items()},
        head_center=M(shape.centre),
        head_radii=np.array([hw_c, 0.5 * (yb_c - yf_c), shape.ztop - zc]) * frame.s,
        skull_top=M(np.array([0.0, A["crown"][0], shape.ztop])),
        brow_front=M(SK.lift(shape, np.zeros(1), np.array([float(brows["L"][:, 1].max())]))[0]),
        chin=M(np.array([0.0, A["chin_point"][0], A["chin_point"][1]])),
        skin=dict(verts=Vs_m, faces=Ts),
        hairline=M(front),
        hairline_side={k: M(v) for k, v in side.items()},
        nape=M(nape),
        face_outline=M(outline),
        ears={s: {k: M(v) if k != "out" else v for k, v in d.items()} for s, d in ear_info.items()},
        eyes=eye_info,
        brows={s: M(SK.lift(shape, c[:, 0], c[:, 1])) for s, c in brows.items()},
        neck_ring=neck_ring(nt),
        neck_center=np.array([nt["center"][0], nt["center"][1], nt["z"]], float),
    )
    cb = guides.get("cat_ear_base") or M(np.array([0.0709, -0.0249, 0.1597]))
    anchors = {}
    for sd, sg in (("L", 1.0), ("R", -1.0)):
        p = frame.to_local(np.array([sg * abs(cb[0]), cb[1], cb[2]]))
        o, n, upv, fwd, axis = HI.tangent_frame(shape, p, sg, float(guides.get("cat_ear_tilt_out_deg", 12.0)))
        anchors[sd] = dict(origin=M(o), normal=n, up=upv, forward=fwd, axis=axis)
    info["cat_ear_anchors"] = anchors
    return info
